[package]
name = "unstoppableswap-gui-rs"
version = "1.0.0-rc.13"
authors = [ "binarybaron", "einliterflasche", "unstoppableswap" ]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

description = "GUI for XMR<>BTC Atomic Swaps written in Rust"

[lib]
name = "unstoppableswap_gui_rs_lib"
crate-type = [ "lib", "cdylib", "staticlib" ]

[build-dependencies]
tauri-build = { workspace = true, features = ["config-json5"] }

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
swap = { workspace = true, features = ["tauri"] }
sysinfo = { workspace = true }
tauri = { workspace = true, features = ["config-json5"] }
tauri-plugin-clipboard-manager = { workspace = true }
tauri-plugin-opener = { workspace = true }
tauri-plugin-process = { workspace = true }
tauri-plugin-shell = { workspace = true }
tauri-plugin-store = { workspace = true }
tauri-plugin-updater = { workspace = true }
tracing = { workspace = true }

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-cli = "^2.0.0"
tauri-plugin-single-instance = "^2.0.0"
