[workspace]
resolver = "2"
members = [ "monero-harness", "monero-rpc", "swap", "monero-wallet", "src-tauri" ]

[workspace.dependencies]
anyhow = "1"
arti-client = { version = "0.25.0", default-features = false }
async-compression = "0.3"
async-trait = "0.1"
asynchronous-codec = "0.7.0"
atty = "0.2"
backoff = "0.4"
base64 = "0.22"
bdk = "0.28"
big-bytes = "1"
bitcoin = "0.29"
bitcoin-harness = { git = "https://github.com/delta1/bitcoin-harness-rs.git", rev = "80cc8d05db2610d8531011be505b7bee2b5cdf9f" }
bmrng = "0.5.2"
comfy-table = "7.1"
config = { version = "0.14", default-features = false }
conquer-once = "0.4"
data-encoding = "2.6"
dialoguer = "0.11"
directories-next = "2"
ecdsa_fun = { version = "0.10", default-features = false }
ed25519-dalek = "1"
futures = { version = "0.3", default-features = false }
get-port = "3"
hex = "0.4"
hex-literal = "0.4"
jsonrpc_client = "0.7"
jsonrpsee = "0.16.2"
jsonrpsee-core = "0.16.2"
libp2p = "0.53.2"
libp2p-community-tor = { git = "https://github.com/umgefahren/libp2p-tor", branch = "main" }
mockito = "1.4"
monero = "0.12"
monero-epee-bin-serde = "1"
monero-harness = { path = "monero-harness" }
monero-rpc = { path = "monero-rpc" }
once_cell = "1.19"
pem = "3.0"
proptest = "1"
qrcode = "0.14"
rand_chacha = "0.3"
regex = "1.10"
reqwest = { version = "0.12", default-features = false }
rust_decimal = "1"
rust_decimal_macros = "1"
serde = "1.0"
serde_cbor = "0.11"
serde_json = "1.0"
serde_with = "1"
serial_test = "3.1"
sha2 = "0.10"
sigma_fun = { version = "0.7", default-features = false }
sqlx = "0.8"
structopt = "0.3"
strum = "0.26"
swap = { path = "swap" }
sysinfo = "=0.32.1"
tauri = { version = "2.0.0", default-features = false }
tauri-build = "2.0"
tauri-plugin-clipboard-manager = "2.0.0"
tauri-plugin-opener = "2.2.5"
tauri-plugin-process = "2.0.0"
tauri-plugin-shell = "2.0.0"
tauri-plugin-store = "2.0.0"
tauri-plugin-updater = "2.1.0"
tempfile = "3"
testcontainers = "0.15"
thiserror = "1"
time = "0.3"
tokio = { version = "1", default-features = false }
tokio-tungstenite = "0.15"
tokio-util = "0.7"
toml = "0.8"
tor-rtcompat = "0.25.0"
tower = "0.4.13"
tower-http = "0.3.4"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", default-features = false }
typeshare = "1.0.3"
unsigned-varint = "0.8.0"
url = "2"
uuid = "1.9"
vergen = { version = "8.3", default-features = false }
void = "1"

[patch.crates-io]
# patch until new release https://github.com/thomaseizinger/rust-jsonrpc-client/pull/51
jsonrpc_client = { git = "https://github.com/delta1/rust-jsonrpc-client.git", rev = "3b6081697cd616c952acb9c2f02d546357d35506" }
monero = { git = "https://github.com/comit-network/monero-rs", rev = "818f38b" }
