[toolchain]
channel = "1.74.0"                                               # also update this in the readme, changelog, and github actions
components = ["clippy"]
targets = ["armv7-unknown-linux-gnueabihf", "aarch64-apple-ios"]
