[toolchain]
channel = "1.79" # also update this in the readme, changelog, and github actions
components = ["clippy"]
targets = [
    "armv7-unknown-linux-gnueabihf",
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    "aarch64-apple-ios-sim",
]
