[package]
name = "monero-wallet-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.137"
tracing = "0.1"
uuid = { version = "1.16.0", features = ["v4"] }

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1"
cxx-build = "1.0.137"

[dev-dependencies]
tempfile = "3.19.1"
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
anyhow = "1"
testcontainers = "0.15"
reqwest = { version = "0.12", default-features = false, features = ["json"] }
monero-harness = { path = "../monero-harness" }

[patch.crates-io]
# Match the patches from the core workspace
jsonrpc_client = { git = "https://github.com/delta1/rust-jsonrpc-client.git", rev = "3b6081697cd616c952acb9c2f02d546357d35506" }
monero = { git = "https://github.com/comit-network/monero-rs", rev = "818f38b" }
