[package]
name = "monero-wallet-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.137"
tracing = "0.1.41"
tokio = "1.44.2"

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0.137"

[dev-dependencies]
anyhow = "1.0.98"
tempfile = "3.19.1"
testcontainers = "0.15"
tracing-subscriber = "0.3.19"
uuid = "1.16.0"
