[package]
name = "monero-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.137"
tracing = "0.1.41"
tokio = { version = "1.44.2", features = ["sync", "time", "rt"] }
monero = { version = "0.12", features = ["serde_support"] }

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0.137"

[dev-dependencies]
anyhow = "1.0.98"
tempfile = "3.19.1"
testcontainers = "0.15"
tracing-subscriber = "0.3.19"
uuid = { version = "1.16.0", features = ["v4"] }
tokio = { version = "1.44.2", features = ["full"] }
monero-harness = { path = "../monero-harness" }
