[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

# windows defaults to smaller stack sizes which isn't enough
[target.'cfg(windows)']
rustflags = ["-C", "link-args=/STACK:8388608"]
