[package]
name = "monero-wallet"
version = "0.1.0"
authors = [ "CoBloX Team <team@coblox.tech>" ]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
monero = { workspace = true }
monero-rpc = { workspace = true }
rand = "0.7"

[dev-dependencies]
curve25519-dalek = "3"
monero-harness = { workspace = true }
rand = "0.7"
testcontainers = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "macros", "sync", "process", "fs"] }
tracing-subscriber = { workspace = true, features = ["fmt", "ansi", "env-filter", "chrono", "tracing-log"] }
