# This file is used to build the release binaries for the Tauri GUI
name: "Publish GUI release to GitHub"

on:
  release:
    types: [created]

env:
  UBUNTU_PLATFORM_ID: "ubuntu-24.04"
  WINDOWS_PLATFORM_ID: "windows-latest"
  DEPS_MONERO_LINUX: 'build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev libprotobuf-dev protobuf-compiler ccache git'
  DEPS_GUI_UBUNTU_SPECIFIC: 'libgtk-3-dev libappindicator3-dev librsvg2-dev libwebkit2gtk-4.1-0=2.44.0-2 libwebkit2gtk-4.1-dev=2.44.0-2 libjavascriptcoregtk-4.1-0=2.44.0-2 libjavascriptcoregtk-4.1-dev=2.44.0-2 gir1.2-javascriptcoregtk-4.1=2.44.0-2 gir1.2-webkit2-4.1=2.44.0-2'
  DEPS_MONERO_MACOS: 'cmake boost hidapi openssl zmq libpgm miniupnpc expat libunwind-headers protobuf ccache'
  DEPS_MONERO_WINDOWS_MSYS2: >-
    mingw-w64-x86_64-toolchain
    make
    mingw-w64-x86_64-cmake
    mingw-w64-x86_64-ccache
    mingw-w64-x86_64-boost
    mingw-w64-x86_64-openssl
    mingw-w64-x86_64-zeromq
    mingw-w64-x86_64-libsodium
    mingw-w64-x86_64-hidapi
    mingw-w64-x86_64-protobuf-c
    mingw-w64-x86_64-libusb
    mingw-w64-x86_64-unbound
    git
  APT_SET_CONF_COMMAND: |
    sudo tee -a /etc/apt/apt.conf.d/80-custom << EOF
    Acquire::Retries "3";
    Acquire::http::Timeout "120";
    Acquire::ftp::Timeout "120";
    EOF
  CCACHE_SETTINGS_COMMAND: |
    ccache --max-size=150M
    ccache --set-config=compression=true

jobs:
  publish-tauri:
    # Do not publish preview releases to Github.
    # Building takes too long for preview releases.
    # if: ${{ !contains(github.ref_name, 'preview') }} Temporarily disabled
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-13" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-24.04" # We build on an older version to support older glib versions
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: Swatinem/rust-cache@v2.7.3

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@1.80
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Configure apt for retries (ubuntu only)
        if: matrix.platform == env.UBUNTU_PLATFORM_ID
        run: ${{ env.APT_SET_CONF_COMMAND }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == env.UBUNTU_PLATFORM_ID # This must match the platform value defined above.
        run: |
          sudo apt update;
          sudo apt install -y ${{ env.DEPS_MONERO_LINUX }} ${{ env.DEPS_GUI_UBUNTU_SPECIFIC }}

      - name: Install Monero build dependencies (macOS)
        if: startsWith(matrix.platform, 'macos')
        run: |
          brew update
          brew install ${{ env.DEPS_MONERO_MACOS }}

      - name: Install Monero build dependencies (Windows)
        if: matrix.platform == env.WINDOWS_PLATFORM_ID
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: ${{ env.DEPS_MONERO_WINDOWS_MSYS2 }}

      - name: Setup ccache (Linux/macOS)
        if: matrix.platform == env.UBUNTU_PLATFORM_ID || startsWith(matrix.platform, 'macos')
        run: ${{ env.CCACHE_SETTINGS_COMMAND }}

      - name: Setup ccache (Windows)
        if: matrix.platform == env.WINDOWS_PLATFORM_ID
        shell: msys2 {0}
        run: ${{ env.CCACHE_SETTINGS_COMMAND }}

      - name: work around spurious network errors in curl 8.0
        shell: bash
        run: |
          echo "CARGO_HTTP_MULTIPLEXING=false" >> $GITHUB_ENV

      - name: install frontend dependencies
        working-directory: src-gui
        run: yarn install

      - name: install tauri-cli globally
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: tauri-cli@2.1.0
          
      - name: install typeshare-cli globally
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: typeshare-cli

      - name: install dprint globally
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: dprint@0.39.1

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.BOTTY_GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD:  ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          releaseId: ${{ github.event.release.id }}
          projectPath: src-tauri
          args: ${{ matrix.args }}
          tauriScript: cargo tauri
